export const FETCH_MOVIES_REQUEST = 'FETCH_MOVIES_REQUEST';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';
export const ADD_LIKE_LIST = 'ADD_LIKE_LIST';
export const ADD_BLOCK_LIST = 'ADD_BLOCK_LIST';
export const SET_MOVIES_STATE = 'SET_MOVIES_STATE';
export const SET_TOTAL_PAGES = 'SET_TOTAL_PAGES';
export const CHANGE_PAGES = 'CHANGE_PAGES';
export const CHANGE_SORT_TYPE = 'CHANGE_SORT_TYPE';
export const CHANGE_TYPE_FLAG = 'CHANGE_TYPE_FLAG';
export const CHANGE_NAV_FLAG = 'CHANGE_NAV_FLAG';



